#!/usr/bin/perl
#===============================================================================
#
#          FILE: CleanFiles.sh
# 
#         USAGE: ./CleanFiles.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Brett Salemink (), admin@roguedesigns.us
#  ORGANIZATION: Rogue Designs
#       CREATED: 07/11/2018 19:49
#      REVISION:  ---
#===============================================================================

&rena(`find . -type d`);
&rena(`find . -type f`);

sub rena
{
	    ($elems)=@_;
	    @t=split /\n/,$elems;

		for $e (@t)
		{
		$_=$e;
		# remove ./ of find
		s/^\.\///;
		# non ascii transliterate
		tr [\200-\377][_];
		tr [\000-\40][_];
		# special characters we do not want in paths
		s/[ \-\,\;\?\+\'\"\!\[\]\(\)\@\#]/_/g;
		# multiple dots except for extension
		while (/\..*\./)
		{
			s/\./_/;
		}
		# only one _ consecutive
		s/_+/_/g;
		next if ($_ eq $e ) or ("./$_" eq $e);
		print "$e -> $_\n";
		rename ($e,$_);
		}
}

